### ISSUE TITLE
Add documentation for Shape detection, Camera Calibration, Solve PNP and Hardware/Metrics. 

### ISSUE THREAD

**Issue by XzibitGG** [PhotonVision/photonvision-docs#10]
- [x] Shape detection
- [x] Camera Calibration -> dot board vs Chessboard, differences
- [x] Solve PNP -> Creating custom models, how does it work?
- [x] Hardware/Metrics. -> GPIO/PWM config files, how it works on different SBCs

**Comment by mdurrani808** [comment]
Closed by #131 
Closed by #127 
Closed by #58 
Custom Solve PNP models are no longer supported.
