### ISSUE TITLE
Find alternative to Balena Etcher for privacy concerns

### ISSUE THREAD

**Issue by Bankst** [PhotonVision/photonvision-docs#101]
Balena Etcher has some privacy concerns and is also not GDPR compliant.
https://github.com/balena-io/etcher/issues/2497

I suggest https://gitlab.com/bztsrc/usbimager for SD card imaging, not sure if it will work for Gloworm/LL though.

**Comment by mdurrani808** [comment]
No good alternative to Balenca Etcher currently exists (specifically concerning Compute Module based devices such as the Gloworm / LL) and since WPILib still plans on reccomending it we will do the same.
