### ISSUE TITLE
Add Romi related related docs for R/W settings

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision-docs#123]
* Note FS must be set R/W before installing
* Note FS must be set R/W for settings changes to persist
* Notes about logging, settings, etc. needing to be in RW for those to save

**Comment by mdurrani808** [comment]
@gerth2 Could you confirm that this is not necessary anymore?

**Comment by gerth2** [comment]
Actually, I think this is still needed?

Previously, photon vision would crash without R/W set to allow writing. 

With the collective updates of:
https://github.com/PhotonVision/photonvision/pull/286
https://github.com/PhotonVision/photonvision/pull/303
https://github.com/PhotonVision/photonvision/pull/367

Photonvision should still run and demonstrate basic features without read/write set to write. However, file system needs to be set to be writable to get logs to disk, and to save settings changes.
