### ISSUE TITLE
Add documentation for using target data on the robot

### ISSUE THREAD

**Issue by Alphyte** [PhotonVision/photonvision-docs#13]
- [x] Rotating to a target
- [x] Driving to a specific difference
- [ ] "Searching" for a target
- [x] Driving to a target
- [x] Using WPILib's state estimator classes (link to WPILib docs)

**Comment by mdurrani808** [comment]
What do you mean by "Searching" for a target? Is it covered by any of the topics here; https://docs.photonvision.org/en/latest/docs/programming/examples/index.html

**Comment by Bankst** [comment]
Per discord discussion with @Alphyte, leaving out "searching" as it is an uncommon task. Closing as remaining docs are complete.
