### ISSUE TITLE
Install Docs needs updated

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision-docs#130]
https://docs.photonvision.org/en/latest/docs/getting-started/installation/limelight.html should not refer to gloworm image, since it's old.

Update install guide to point to images in the main photonvision release page. references to the pi image repo shouldn't' be needed anymore, that's no longer the "user-facing" way to get photon.

**Comment by gerth2** [comment]
Bumping with some specifics, since folks are gonna want this earlier rather than later. I'll try to start tackling this tonight. Specifically - 

1) Change "Installation" section to "Getting Started"
2) Split out to have one unique page per hardware. Hardware should include (in order) Pi 3, Pi 4, Limelight, Gloworm, SnakeEyes, Windows PC, Linux PC, Mac PC, Romi
3) Add new section for "Command Line Usage" for some background on how to use the command line portion.

Pi 3 can still reference the image. Pi 4 should make mention that the Pi 3 instructions might work, but otherwise provide a "download latest raspian and run the linux script" procedure.

Review the other hardware docs too - don't delete any info, just mark things that "are not yet tested for 2023"

**Comment by mdurrani808** [comment]
@gerth2 Seems to be good to close? Clarify if there is something to be added here, your last PR seems to have taken care of most of this

**Comment by gerth2** [comment]
yup I think we're done here.
