### ISSUE TITLE
Expand Hardware Section To Specify Pi Versions and Add Performance Matrix

### ISSUE THREAD

**Issue by willtoth** [PhotonVision/photonvision-docs#135]
The supported hardware page mentions PI 3 as the better option for hardware. I assume this only means 3B+

With the supply chain issues it may be nice to clarify since folks are gonna have a hard time finding most of these. I also have a few 3 B v1.2 but I assume these are not better than the 3 B+ or 4?

**Comment by mcm001** [comment]
Unconfirmed, but I'm pretty sure any Pi 3 will support GPU acceleration. I test mostly with a Pi 3b v1.2, but I haven't done any head-to-heads. With regular USB cameras, the Pi 4 is a fair bit faster than the 3s though. We can totally add a performance comparison matrix though.

**Comment by willtoth** [comment]
> I test mostly with a Pi 3b v1.2

Awesome! I will set this up and play around with it then on the pi I do have. The v1 cameras seem to be easy enough to source and I do already have one.

**Comment by mdurrani808** [comment]
Avaliable now!
