### ISSUE TITLE
Improve Docs Flow

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision-docs#143]
Users should get the following flow:

- Here is what PhotonVision is
- Here is how you install PhotonVision
**- Here is hardware you can use with PhotonVision**
**- Here is how you navigate the PhotonVision UI**
- Here is how you track your first target
**-        Here is what a pipeline is and here are the two types of pipelines**
**-        Here is a deeper explanation of all the things you should tune**
- Here is how you use that tracked target in your code
- Here is some smart commentary about the usage of vision in tandem w/ a robot
- Here are more code examples
- Here is how you add to PhotonVision Projects
- Other Stuff

Everything that is highlighted is things that need work.

**Comment by mdurrani808** [comment]
- [ ] Highlight SnakeEyes more in Hardware
- [ ] Add how to navigate PhotonVision UI page
- [ ] Add about pipelines page

**Comment by gerth2** [comment]
Re: #142 - this covers the intent. To tack on a few ideas:

"Here is how you install photonvision": The pedagogy I'd propose:
1) Photonvision is a java application, with some system dependencies for full functionanlity.
2) Installation will vary slightly depending on the hardware executing photonvision
3) Independent, clearly titled, per-hardware instructions (IE, if a user has a gloworm, they shouldn't have to read through generic Pi install info, as they probably don't care in that moment).
4) General background info on installing and running photonvision (command line API?) such that people have enough guidance to stray from the beaten path with success.

**Comment by gerth2** [comment]
"Here is what photonvision is": i'd propose what a first time user actually needs to care about is "Why should I use photonvision?" . I think the section content will largely be the same, just some reworked titles or slight rephrasing to make it the "persuasive essay" portion.

**Comment by gerth2** [comment]
But, I should say, the flow described in the PR is super awesome and exactly what I was thinking. It guides a brand new user through the proper set of steps to go from zero to integrated code, hopefully building some key understanding along the way.

**Comment by gerth2** [comment]
The biggest thing to watch out for - we have lots of docs (which is great!). Presenting all the info at once to a new user can fill them with dread and impressions of "I don't understand any of this, there's no way I can possibly learn it in time, let's just not do vision processing". 

I don't have a super great way to do this just yet.... but I think the critical thing will be balancing where the "Advanced" sections get injected in ("Just-in-time learning"), while making it very clear that if someone's brain is already full, they can skip a certain section, and still probably have success.

**Comment by mdurrani808** [comment]
I think we've accomplished this pretty well and the state of the docs has changed enough to warrant a new issue.
