### ISSUE TITLE
Document multicam behavior

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision-docs#163]
All cameras run one pipeline each, all publish to NT, and all send both streams

**Comment by mdurrani808** [comment]
Curious as to where this should live wrt the current documentation...I'm thinking somewhere on the pipelines page? Maybe this requires a seperate multi cam page?
@gerth2 you have good thoughts on these things, any ideas?

**Comment by gerth2** [comment]
Actually is it one pipeline per camera? I just created two pipelines running on the same camera?

Regardless, I'd say put something under the Pipeline Tuning section, maybe if it's small just another sectin under the About Pipelines page?

Just as a "multi-cam support" section or page, with the idea that we'd recommend folks usually only do one or two cameras (with one pipeline each), but do technically support more exotic configs maybe?
