### ISSUE TITLE
Code snippets seem to be wrong

### ISSUE THREAD

**Issue by allderdicerobotics** [PhotonVision/photonvision-docs#166]
https://docs.photonvision.org/en/latest/docs/programming/photonlib/creating-photon-camera.html

This page doesn't seem to contain the right snippets of code for instantiating a new PhotonCamera:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/35245530/157454791-bef43df1-ebfa-4c52-b8a6-c1dad641f861.png">

This issue seems to be present in a bunch of the code snippets.

**Comment by pietroglyph** [comment]
I think there might be a reasonable middle ground where we have the code snippet remote literal includes use a specific commit from the examples. Same change overhead as copy paste, but different ongoing overhead (i.e. the remote literal includes take up less space in the code).

**Comment by mdurrani808** [comment]
Closed by #168

**Comment by gerth2** [comment]
Despite being at competition and on my phone and unable to actually make a
contribution, I approve of this message

**Comment by gerth2** [comment]
@github that was most definitely not when I sent this message^^
