### ISSUE TITLE
Code examples in PhotonLib docs are cut off/are incorrect

### ISSUE THREAD

**Issue by danielml2** [PhotonVision/photonvision-docs#176]
The code examples are either split between two different code blocks, or are just not what the article is talking about

Examples:
https://docs.photonvision.org/en/latest/docs/programming/photonlib/creating-photon-camera.html:
![image](https://user-images.githubusercontent.com/64473184/189413177-88fb73bf-ed19-45d3-a9ac-34722d419ece.png)

https://docs.photonvision.org/en/latest/docs/programming/photonlib/simulation.html#simulated-vision-system:
![image](https://user-images.githubusercontent.com/64473184/189413346-990b4fbd-68a4-451d-8429-bbbc8a28f6b0.png)

https://docs.photonvision.org/en/latest/docs/programming/photonlib/util-calculations.html:
![image](https://user-images.githubusercontent.com/64473184/189413589-a2825e8f-60e7-4f4c-b2af-d9fcf01869c6.png)
![image](https://user-images.githubusercontent.com/64473184/189413608-26aac320-4f9a-4bef-bced-e19707550bfa.png)

**Comment by mdurrani808** [comment]
I thought this was fixed in #168. I'll take a look this weekend and will get to it soon.

**Comment by mdurrani808** [comment]
Seems like 168 only covered examples and not this stuff, I'll take care of these then this weekend. Thanks for the heads up.
