### ISSUE TITLE
photonvision.org revamp

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision-docs#180]
Not actually in this repo but tracking some thoughts...

https://photonvision.org/ could use a few updates:

1) References Gloworm, which (unfortunately) isn't looking like it will be prime-path this year. Perhaps change out to be just generically "Raspberry pi based solutions"?
2) Screenshots are all the retroreflective. Maybe get some AprilTag ones as well? Videos are always good.
3) Maybe advertise the built-in camera calibration with some videos

**Comment by gerth2** [comment]
Also copyright date still says 2021.

**Comment by mdurrani808** [comment]
@gerth2 this belongs in the proper website repo

**Comment by gerth2** [comment]
til we have a repo for that. https://github.com/PhotonVision/photonvision-website/issues/5 added
