### ISSUE TITLE
Permalink icon is not

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision-docs#185]
![image](https://user-images.githubusercontent.com/4583662/195086033-33a4b5c9-c68a-4f49-9933-876cac68cc9e.png)

Not sure why it's not, but we should make it not not.

**Comment by democat3457** [comment]
<img width="512" alt="Screen Shot 2022-11-06 at 12 35 27 PM" src="https://user-images.githubusercontent.com/32407067/200188774-7051d09c-e366-484b-bda5-24fc746df21a.png">
arguably worse here :joy:
