### ISSUE TITLE
Bump code snippets to later official releases

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision-docs#187]
PR's such as https://github.com/PhotonVision/photonvision/pull/501 have fixed concrete issues with the code in examples. However, since the code snippet includes are permalinked against a SHA1, we'll need to move this forward.

Some time around doing the official release, we'll want to pull in the latest photonvision release to these permalinks and update line numbers as needed.

**Comment by mdurrani808** [comment]
Ill get this done when the April Tag examples get merged in
