### ISSUE TITLE
Document camera nickname and effect on NetworkTables 

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision-docs#189]

**Comment by mdurrani808** [comment]
More than this? 
"The PhotonCamera class has two constructors: one that takes a NetworkTable and another that takes in the name of the network table that PhotonVision is broadcasting information over. For ease of use, it is recommended to use the latter. The name of the NetworkTable (for the string constructor) should be the same as the camera’s nickname (from the PhotonVision UI)."
