### ISSUE TITLE
import settings broken video

### ISSUE THREAD

**Issue by mdurrani808** [PhotonVision/photonvision-docs#230]

**Comment by stolenricecakes** [comment]
From the https://docs.photonvision.org/en/latest/docs/getting-started/pipeline-tuning/reflectiveAndShape/thresholding.html page, both the https://docs.photonvision.org/en/latest/docs/_static/assets/colorPicker.mp4 and https://docs.photonvision.org/en/latest/docs/_static/assets/tuningHueSatVal.mp4 videos return HTTP 404's
