### ISSUE TITLE
Change Mini PC Tests link to Guide

### ISSUE THREAD

**Issue by asid61** [PhotonVision/photonvision-docs#233]
I have created a more streamlined Guide for my Mini PC tests. If it can be linked in Supported Hardware (https://docs.photonvision.org/en/latest/docs/hardware/supportedhardware.html) instead of the currently present Tests link that would be great.

Correct link: https://docs.google.com/document/d/1lOSzG8iNE43cK-PgJDDzbwtf6ASyf4vbW8lQuFswxzw/edit?usp=sharing

**Comment by mdurrani808** [comment]
Closed by #231
