### ISSUE TITLE
"Code Example" link on RobotPoseEstimator documentation redirects to google.com instead of a code example

### ISSUE THREAD

**Issue by kesleta** [PhotonVision/photonvision-docs#255]
The link for the "code example" for the [RobotPoseEstimator documentation page](https://docs.photonvision.org/en/latest/docs/programming/photonlib/robot-pose-estimator.html#using-a-robotposeestimator) for some reason redirects to [www.google.com](http://www.google.com/) rather than an actual code example. It is under the "Using a RobotPoseEstimator" header. Thanks

**Comment by mdurrani808** [comment]
Good catch, will fix.
