### ISSUE TITLE
Broken link on https://photonvision.org/downloads.html to RaspberryPi and GloWorm installation pages

### ISSUE THREAD

**Issue by dkoneill** [PhotonVision/photonvision-docs#260]
The links at the top of https://photonvision.org/downloads.html are incorrect.

Current links:
[Raspberry Pi Installation Documentation](https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html)

[GloWorm Installation Documentation](https://gloworm.vision/docs/quickstart/)

Corrected Raspberry Pi link:
[Raspberry Pi Installation Documentation](https://docs.photonvision.org/en/latest/docs/getting-started/installation/sw_install/raspberry-pi.html)

GloWorm.vision has no DNS entry, so that site has likely been decommissioned.

**Comment by mdurrani808** [comment]
These should go on our website repository, not here.
