### ISSUE TITLE
On the getting target data page getYaw() is mentioned instead of getSkew()

### ISSUE THREAD

**Issue by dkoneill** [PhotonVision/photonvision-docs#266]
Here is the reference link
https://docs.photonvision.org/en/latest/docs/programming/photonlib/getting-target-data.html#getting-data-from-a-target

Current: double getYaw()/GetYaw(): The skew of the target in degrees (counter-clockwise positive).

Replacement: double getSkew()/GetSkew(): The skew of the target in degrees (counter-clockwise positive).

Thanks - great docs!

**Comment by mdurrani808** [comment]
Good catch! Will fix.
