### ISSUE TITLE
"new" Material Docs Issues

### ISSUE THREAD

**Issue by Modelmat** [PhotonVision/photonvision-docs#29]
1. The little "pen" icon is not vertically centred.
 ![image](https://user-images.githubusercontent.com/25718989/88764941-1fbf3100-d1b9-11ea-8dac-9bbcf580bb1a.png)

2. The branch indicator displays over the bottom right text and also over the theme switcher. Should it be moved to its own place in the header/footer rather than be floating?
 ![image](https://user-images.githubusercontent.com/25718989/88764982-2d74b680-d1b9-11ea-8074-8355d64a5f5d.png)

3. The text margins are not equal [an issue in a few places]
![image](https://user-images.githubusercontent.com/25718989/88765140-64e36300-d1b9-11ea-8433-aebff7c82f85.png)

**Comment by mdurrani808** [comment]
We now use Furo theme so this is not needed.
