### ISSUE TITLE
Fix confusing wording about Photonlib camera naming

### ISSUE THREAD

**Issue by amquake** [PhotonVision/photonvision-docs#315]
https://github.com/PhotonVision/photonvision-docs/blob/54cfc26bec0f7f4f1e6473d803d9c5be5e145be4/source/docs/programming/photonlib/getting-target-data.rst?plain=1#L14-L23

In these examples, the camera name is simply set to `"photonvision"`. This has confused some new users into thinking it points to the `photonvision` networktable, instead of the specific camera table. This should be something else instead, like `"YOUR_CAMERA_NAME"`.

**Comment by mdurrani808** [comment]
This should be PRed to the main code as this uses an RLI.
