### ISSUE TITLE
Example video in pipeline outputs 404s

### ISSUE THREAD

**Issue by TheComputer314** [PhotonVision/photonvision-docs#346]
https://docs.photonvision.org/en/latest/docs/pipelines/output.html

https://docs.photonvision.org/en/_static/assets/offsetandmultiple.mp4

Expected behavior: For the mp4 at the link to exist
Actual behavior: 404

**Comment by TheComputer314** [comment]
typo lol

**Comment by Sam948-byte** [comment]
the path to the file in question has an extra ../

I will create a PR to address this once my current PR has been merged

**Comment by Sam948-byte** [comment]
@mcm001 it doesn't look like this one got properly linked, as it's still open.  You might want to go ahead and close it.

**Comment by TheComputer314** [comment]
It appears to be working now on my end...?

**Comment by Sam948-byte** [comment]
I'm sorry, that might have been a bit confusing.  When I said it didn't get properly linked, what I meant was that I didn't properly link the issue that you created to my PR.  If it had linked correctly, the issue ought to have closed when the PR was merged.  The link in the docs is fully functioning afaik.  If you want to go ahead and close the issue, that works too.

**Comment by TheComputer314** [comment]
Oh ok.
