### ISSUE TITLE
Website icon should have transparent background

### ISSUE THREAD

**Issue by prateekma** [PhotonVision/photonvision-docs#37]
![image](https://user-images.githubusercontent.com/19977330/89598882-fa22cf00-d82b-11ea-9c08-ee03ad1772f4.png)
White shows up in dark mode

**Comment by mdurrani808** [comment]
This doesn't seem like something we can control (at least live), more to do with how Safari decides how to render the icon. See 
https://stackoverflow.com/questions/59233531/safari-favicon-incorrectly-rendering-with-white-background
