### ISSUE TITLE
Document LED control Limitation w/o vendor camera

### ISSUE THREAD

**Issue by gerth2** [PhotonVision/photonvision-docs#62]
After PR <TBD>, there will still be a limitation in the LED control algorithm.

Namely, if you have multiple pipelines, some used for driver mode, and some used for vision processing, and simultaneously want to use PhotonVision to control LED's, you'll probably have a bad time. The logic internal to PhotonVision isn't quite there yet. There needs to be some UI updates to allow the user to express which camera (or maybe cameras?) should actually have control over the LED state.

The workaround today is simple: just manipulate the `ledMode` entry in NT from the RIO side in your robot code.

Tentative suggested verbage:

```
As of the <XYZ> Release, the logic for controlling LED mode when multiple cameras are connected is not fully fleshed out. For now, if you are using multiple cameras, it is recommended that teams set the value of the `photonvision/ledMode` networktables entry from their own code. 
```

**Comment by mdurrani808** [comment]
Should probably be on a new Known Issues page in the other category.

**Comment by mdurrani808** [comment]
#71 Adds a known issues page/known software issues page for this to go under.

**Comment by mdurrani808** [comment]
Closing now that #73 is merged
